fix(ssl errors)
Downgrade eventlet from 0.17.2 to 0.15.2 as the newer version was
causing SSL errors. From @samstav's commit message for PR#394:

The maintainer of eventlet appears to be owning up to this one:

https://github.com/eventlet/eventlet/issues/226

Proxy calls were failing on python 2.7.9's backported ssl module with the following error:
```pytb
Traceback (most recent call last):
  File "~/.venvs/checkmate/src/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "~/.venvs/checkmate/src/bottle/bottle.py", line 1738, in wrapper
    rv = callback(*a, **ka)
  File "~/Projects/rackspace/checkmate/ui/rook/middleware.py", line 475, in github_callback
    data=json.dumps(body), headers=headers)
  File "~/.venvs/checkmate/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "~/.venvs/checkmate/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "~/.venvs/checkmate/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "~/.venvs/checkmate/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "~/.venvs/checkmate/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "~/.venvs/checkmate/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
    body=body, headers=headers)
  File "~/.venvs/checkmate/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 322, in _make_request
    self._validate_conn(conn)
  File "~/.venvs/checkmate/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 727, in _validate_conn
    conn.connect()
  File "~/.venvs/checkmate/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 253, in connect
    match_hostname(cert, self.assert_hostname or hostname)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 245, in match_hostname
    raise ValueError("empty or no certificate, match_hostname needs a "
ValueError: empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED
```